"""Receipt schema definitions for detect module.

Schemas: scan_receipt, classify_receipt, drift_receipt, alert_receipt, resource_receipt
"""

DETECT_SCHEMAS = {
    "scan": {
        "receipt_type": "scan",
        "ts": "ISO8601 timestamp",
        "tenant_id": "string",
        "payload_hash": "dual-hash format",
        "receipts_scanned": "integer - count processed",
        "patterns_checked": "integer - patterns evaluated",
        "matches_found": "integer - matches detected",
        "matches": "list of match dicts (pattern_id, receipt_hash, score, confidence)",
        "elapsed_ms": "integer - scan duration",
    },
    "classify": {
        "receipt_type": "classify",
        "ts": "ISO8601 timestamp",
        "tenant_id": "string",
        "payload_hash": "dual-hash format",
        "match_id": "string - reference to scan match",
        "classification": "enum: drift | degradation | violation | deviation | anti_pattern",
        "confidence": "float 0-1",
        "evidence": "list of supporting data points",
    },
    "drift": {
        "receipt_type": "drift",
        "ts": "ISO8601 timestamp",
        "tenant_id": "string",
        "payload_hash": "dual-hash format",
        "metric": "string - what drifted",
        "baseline_value": "float",
        "current_value": "float",
        "drift_score": "float - magnitude of drift (positive = above baseline)",
        "direction": "enum: increasing | decreasing | stable",
        "window_size": "integer - receipts in measurement window",
    },
    "alert": {
        "receipt_type": "alert",
        "ts": "ISO8601 timestamp",
        "tenant_id": "string",
        "payload_hash": "dual-hash format",
        "alert_id": "UUID string",
        "anomaly_type": "classification string",
        "severity": "enum: info | warning | error | critical",
        "source": "dict with receipt_hash and metric",
        "blast_radius": "string - affected scope",
        "escalated": "boolean",
        "escalation_target": "string or null",
    },
    "resource": {
        "receipt_type": "resource",
        "ts": "ISO8601 timestamp",
        "tenant_id": "string",
        "payload_hash": "dual-hash format",
        "resource_type": "enum: tokens | compute | memory | io | cost",
        "consumed": "float",
        "limit": "float",
        "utilization": "float 0-1",
        "period": "string (e.g., 1h, 24h)",
        "threshold_exceeded": "boolean",
    },
}
